routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**********/
/** Admin */
/**********/


Route::get('/admin', 'Admin\ArticleController@index');
Route::resource('tasks', 'Admin\TasksController');
Route::get('/tasks-success', 'Admin\TasksController@index')->name('taskSuccess');

Route::get('/delete-task/{id}', 'Admin\TasksController@destroy');
Route::post('/tasks/{id}/update', 'Admin\TasksController@update');

Route::get('/lessons/{week}', 'Admin\ArticleController@index');

Route::get('/admin/students', 'Admin\ArticleController@index')->name('students');
Route::get('/admin/parents', 'Admin\ArticleController@index')->name('parents');
Route::get('/admin/teachers', 'Admin\ArticleController@index')->name('teachers');

Route::get('/create-new-entry', 'Admin\ArticleController@create')->name('create-new-entry');
Route::get('/blog-entries', 'Admin\ArticleController@index')->name('blog-entries');
Route::post('/store-article', 'Admin\ArticleController@store')->name('store-article');
Route::post('/update-article/{id}', 'Admin\ArticleController@update');
Route::get('/article-edit/{id}', 'Admin\ArticleController@edit');

Route::get('/create-new-category', 'Admin\CategoryController@create')->name('create-new-category');
Route::get('/category-entries', 'Admin\CategoryController@index')->name('category-entries');

Route::post('/store-category', 'Admin\CategoryController@store')->name('store-category');
Route::get('/category-edit/{id}', 'Admin\CategoryController@edit');
Route::post('/update-category/{id}', 'Admin\CategoryController@update');

Route::get('/galleries', 'Admin\GalleryController@index')->name('galleries');
Route::get('/create-galleries', 'Admin\GalleryController@create')->name('create-gallery');
Route::post('/store-gallery', 'Admin\GalleryController@store');
Route::get('/gallery-delete/{id}', 'Admin\GalleryController@delete');
Route::get('/gallery-edit/{id}', 'Admin\GalleryController@edit');
Route::post('/update-gallery/{id}', 'Admin\GalleryController@update');

/** File upload */
Route::get('/uploadfile', 'Admin\UploadFileController@index');
Route::post('/uploadfile', 'Admin\UploadFileController@store');
Route::get('/delete-image/{gallery_id}/{pic_id}', 'Admin\UploadFileController@delete');


/** Front End*/
Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/home', 'Frontend\HomeController@index')->name('home');
Route::get('/homepage', 'Frontend\HomeController@homepage');
Route::get('/blog', 'Frontend\HomeController@index')->name('home');

Route::get('/category/{id}', 'Frontend\HomeController@category');

Route::get('/article/{id}', 'Frontend\HomeController@article');
Route::get('tasks/show/{id}', 'Frontend\TasksController@show');
Route::get('/gallery/album/{id}', 'Frontend\AlbumController@index');
Route::get('/events', 'Frontend\EventsController@index');

/**********/
/** AJAX */
/**********/

Route::get('/increase-likes/{id}', 'Frontend\HomeController@likeIt');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name', 'description', 'task_date'];
}

app/Http/Controllers/Admin/TasksController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{

  public function index()
  {
      $events = Task::all();
      return view('admin.tasks.index', ['events' => $events]);
  }

  public function create()
  {
      return view('admin.tasks.create');
  }

  public function store(Request $request)
  {
      Task::create($request->all());
      return redirect()->route('taskSuccess')->with('Sikeres létrehozás!');
  }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Task::where('id', $id)->first();
        return view('admin.tasks.show', ['event' => $event]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Task::where('id', $id)->first();
        return view('admin.tasks.edit', ['event' => $event]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $event = Task::where('id', $id)->first();
        $event->update(['name' => $request->input('name'), 'description' => $request->input('description'), 'task_date' => $request->input('task_date')]);

        return redirect()->route('taskSuccess');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Task::where('id', $id)->first();
        $event->delete();

        return redirect()->route('taskSuccess');
    }
}

resources/views/admin/tasks/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-lg-2">
            @include('shared.popular')
        </div>

        <div class="col-lg-10">
            <h3>Esemény hozzáadása</h3>
            <form action="{{ route('tasks.store') }}" method="post">
                {{ csrf_field() }}
                Esemény neve:
                <br/>
                <input class="form-control" type="text" name="name"/>
                <br/><br/>
                Esemény leírása:
                <br/>
                <textarea name="description" class="form-control"></textarea>
                <br/><br/>
                Esemény időpontja:
                <br/>
                <input type="date" name="task_date" class="date form-control" />
                <br/><br/>
                <input class="btn btn-primary" type="submit" value="Mentés"/>
            </form>
        </div>

    </div>
@endsection

resources/views/admin/tasks/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-lg-2">
            @include('shared.popular')
        </div>

        <div class="col-lg-10">
            <h3>Esemény módosítása</h3>
            <form action="/tasks/{{$event->id}}/update" method="POST">
                {{ csrf_field() }}
                Esemény neve:
                <br/>
                <input class="form-control" type="text" name="name" value="{{$event->name}}" />
                <br/><br/>
                Esemény leírása:
                <br/>
                <textarea name="description" class="form-control">{{$event->description}}</textarea>
                <br/><br/>
                Esemény időpontja:
                <br/>
                <input type="date" name="task_date" class="date form-control" value="{{$event->task_date}}" />
                <br/><br/>
                <input class="btn btn-primary" type="submit" value="Mentés"/>
            </form>
        </div>

    </div>
@endsection

resources/views/admin/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-lg-2">
            @include('shared.popular')
        </div>

        <div class="col-lg-10">
            <link rel='stylesheet'
                  href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css'/>

            <h3>Események kezelése</h3>

            <table class="table table-striped">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">@lang('admin.title')</th>
                    <th scope="col">Date</th>
                    <th scope="col">Created at</th>
                    <th scope="col" style="width: 5%; text-align: center;">@lang('admin.edit')</th>
                    <th scope="col" style="width: 5%; text-align: center;">@lang('admin.delete')</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($events as $item)

                    <tr>
                        <th scope="row">{{ $item->id }}</th>
                        <th>{{ $item->name }}</th>
                        <th>{{ $item->task_date }}</th>
                        <th>{{ $item->created_at }}</th>
                        <th style="text-align: center;"><a href="/tasks/{{ $item->id }}/edit"><i class='glyphicon glyphicon-edit' style='font-size:20px'></i></a></th>
                        <th style="text-align: center;"><a href="/delete-task/{{ $item->id }}"><i class='glyphicon glyphicon-trash' style='font-size:20px'></i></a></th>
                    </tr>
                @endforeach

                </tbody>
            </table>

            <a href="/tasks/create"><button class="btn btn-primary">@lang('admin.create_new_event')</button></a>

        </div>

    </div>
@endsection

resources/views/admin/tasks/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="col-lg-2">
            @include('shared.popular')
        </div>

        <div class="col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Esemény adatai</h2>
                    </div>
                    <div class="panel-body">
                        <div>Esemény neve: {{$event->name}}</div>
                        <div>Időpontja: {{$event->task_date}}</div>
                        <div>Leírás:<br>{{$event->description}}</div>
                    </div>
                </div>
        </div>

    </div>

@endsection